### ISSUE TITLE
Hi! I need you to help me with the resources!

### ISSUE THREAD

**Issue by Haku-Neko** [MLChinoo/4.3.50-Resource#1]
I am working on a partial PS project which only focus on reliquary data. Can you help me with Reliquary data? I would verry much appreciate it if you could get these files with relic weights. Thank you for check this out!
![image](https://github.com/MLChinoo/4.3.50-Resource/assets/51059177/b4e1c24a-3b00-49c0-80bf-a379458c2ece)

**Comment by MLChinoo** [comment]
add me on discord lvdmpls#6130
